/* Copyright (c) 2010, Code Aurora Forum. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301, USA.
 */
#ifndef __ARCH_ARM_MACH_MSM_GPIOMUX_8X60_H
#define __ARCH_ARM_MACH_MSM_GPIOMUX_8X60_H

#include "gpiomux.h"

void __init msm8x60_init_gpiomux(struct msm_gpiomux_configs *cfgs);
void msm8x60_gpiomux_lcdc_steadycfg(void);

extern struct msm_gpiomux_configs tenderloin_gpiomux_cfgs[] __initdata;
extern struct msm_gpiomux_configs tenderloin_3g_gpiomux_cfgs[] __initdata;
extern struct msm_gpiomux_configs tenderloin_dvt_gpiomux_cfgs[] __initdata;
extern struct msm_gpiomux_configs tenderloin_3g_dvt_gpiomux_cfgs[] __initdata;

/* Macros assume PMIC GPIOs start at 0 */
#define PM8058_GPIO_BASE			NR_MSM_GPIOS
#define PM8058_GPIO_PM_TO_SYS(pm_gpio)		(pm_gpio + PM8058_GPIO_BASE)
#define PM8058_GPIO_SYS_TO_PM(sys_gpio)		(sys_gpio - PM8058_GPIO_BASE)
#define PM8058_MPP_BASE				(PM8058_GPIO_BASE + PM8058_GPIOS)
#define PM8058_MPP_PM_TO_SYS(pm_gpio)		(pm_gpio + PM8058_MPP_BASE)
#define PM8058_MPP_SYS_TO_PM(sys_gpio)		(sys_gpio - PM8058_MPP_BASE)
#define PM8058_IRQ_BASE				(NR_MSM_IRQS + NR_GPIO_IRQS)

#define PM8901_GPIO_BASE			(PM8058_GPIO_BASE + \
						PM8058_GPIOS + PM8058_MPPS)
#define PM8901_GPIO_PM_TO_SYS(pm_gpio)		(pm_gpio + PM8901_GPIO_BASE)
#define PM8901_GPIO_SYS_TO_PM(sys_gpio)		(sys_gpio - PM901_GPIO_BASE)
#define PM8901_IRQ_BASE				(PM8058_IRQ_BASE + \
						NR_PMIC8058_IRQS)

#define UART1DM_RTS_GPIO		56
#define UART1DM_CTS_GPIO		55
#define UART1DM_RX_GPIO			54
#define UART1DM_TX_GPIO			53

#define BT_RST_N			138
#define BT_POWER			130
#define BT_WAKE				131
#define BT_HOST_WAKE			129

#define BT_RST_N_3G			122
#define BT_POWER_3G			110
#define BT_WAKE_3G			131
#define BT_HOST_WAKE_3G			50

#ifdef CONFIG_KEYBOARD_GPIO_PE
/* GPIO Keys */
#define CORE_NAVI_GPIO			40
#define VOL_UP_GPIO			103
#define VOL_DN_GPIO			104
#define VOL_UP_GPIO_3G			(PM8058_GPIO_PM_TO_SYS(6-1))
#define VOL_DN_GPIO_3G			(PM8058_GPIO_PM_TO_SYS(7-1))
#define JACK_DET_GPIO		67
#endif

#ifdef CONFIG_MAX8903B_CHARGER
/* max8903b control GPIOs */
#define MAX8903B_GPIO_DC_CHG_MODE	42
#define MAX8903B_GPIO_USB_CHG_MODE	133
#define MAX8903B_GPIO_USB_CHG_MODE_3G	134
#define MAX8903B_GPIO_USB_CHG_SUS	33
#define MAX8903B_GPIO_CHG_D_ISET_1	34
#define MAX8903B_GPIO_CHG_D_ISET_2	30
#define MAX8903B_GPIO_CHG_EN		41
#define MAX8903B_GPIO_DC_OK		140
#define MAX8903B_GPIO_DC_OK_3G		86
#define MAX8903B_GPIO_STATUS_N		36
#define MAX8903B_GPIO_FAULT_N		35
#endif  //CONFIG_MAX8903B_CHARGER

#define MXT1386_TS_PEN_IRQ_GPIO		123
#define MXT1386_TS_PEN_IRQ_GPIO_3G	45
#define MXT1386_TS_PWR_RST_GPIO		70

#define GPIO_CTP_WAKE			123
#define GPIO_CTP_WAKE_3G		45
#define GPIO_CTP_SCL			73
#define GPIO_CTP_SDA			72
#define GPIO_CTP_RX			71
#define GPIO_CY8CTMA395_XRES		70

#define TENDERLOIN_GPIO_WL_HOST_WAKE	93
#define TENDERLOIN_GPIO_HOST_WAKE_WL	137
#define TENDERLOIN_GPIO_HOST_WAKE_WL_3G	80
#define TENDERLOIN_GPIO_WLAN_RST_N	135
#define TENDERLOIN_GPIO_WLAN_RST_N_3G	28

/* a6 */
#define TENDERLOIN_A6_0_TCK		157
#define TENDERLOIN_A6_0_WAKEUP		155
#define TENDERLOIN_A6_0_TDIO		158
#define TENDERLOIN_A6_0_MSM_IRQ		156
#define TENDERLOIN_A6_0_MSM_IRQ_DVT	37

#define TENDERLOIN_A6_1_TCK		115
#define TENDERLOIN_A6_1_WAKEUP		141
#define TENDERLOIN_A6_1_TDIO		116
#define TENDERLOIN_A6_1_MSM_IRQ		132
#define TENDERLOIN_A6_1_MSM_IRQ_DVT	94


#define TENDERLOIN_A6_0_TCK_3G		68
#define TENDERLOIN_A6_0_TCK_3G_DVT	156
#define TENDERLOIN_A6_0_WAKEUP_3G	155
#define TENDERLOIN_A6_0_TDIO_3G		170
#define TENDERLOIN_A6_0_MSM_IRQ_3G	156
#define TENDERLOIN_A6_0_MSM_IRQ_3G_DVT	37

#define TENDERLOIN_A6_1_TCK_3G		115
#define TENDERLOIN_A6_1_WAKEUP_3G	78
#define TENDERLOIN_A6_1_TDIO_3G		116
#define TENDERLOIN_A6_1_MSM_IRQ_3G	132
#define TENDERLOIN_A6_1_MSM_IRQ_3G_DVT	94

/* camera */
#define TENDERLOIN_CAM_I2C_DATA		47
#define TENDERLOIN_CAM_I2C_CLK		48
#define TENDERLOIN_CAMIF_MCLK		32
#define TENDERLOIN_WEBCAM_RST		106
#define TENDERLOIN_WEBCAM_PWDN		107

/* light sensor */
#define TENDERLOIN_LS_INT       126

/* gyro */
#define TENDERLOIN_GYRO_INT		125
#define TENDERLOIN_GYRO_INT_3G		75

/* G-sensor */
#define TENDERLOIN_GSENS_INT		124


/* audio */
#define TENDERLOIN_AUD_HEAD_MIC_DET_IRQ_GPIO 57
#define TENDERLOIN_AUD_LDO1_EN		        66
#define TENDERLOIN_AUD_LDO2_EN		        108

/* lighting */
#define LM8502_LIGHTING_INT_IRQ_GPIO 	128
#define LM8502_LIGHTING_EN_GPIO 	121
#define LM8502_LIGHTING_INT_IRQ_GPIO_3G	77

/* usb host */
#define ISP1763_INT_GPIO		172
#define ISP1763_DACK_GPIO		169
#define ISP1763_DREQ_GPIO		29
#define ISP1763_RST_GPIO		152
#define GPIO_3G_3V3_EN			82
#define GPIO_3G_3V3_EN_DVT		106
#define GPIO_3G_DISABLE_N		171
#define GPIO_3G_WAKE_N			38
#define GPIO_3G_UIM_CD_N		61

/* pmic */
#define PMIC1_APC_USR_IRQ_N		88
#define PMIC2_APC_USR_IRQ_N		91

/* sensors i2c gpio */
#define GPIO_SENSORS_SDA		43
#define GPIO_SENSORS_SCL		44
#define I2C_RECOVER_CLOCK_CYCLES	36

/*System force boot dis pin*/
#define GPIO_FORCE_BOOT_DIS		154

enum tenderloin_pins {
	MXT1386_TS_PEN_IRQ = 0,
	GPIO_CTP_WAKE_PIN,
	BT_RST_N_PIN,
	BT_POWER_PIN,
	BT_WAKE_PIN,
	BT_HOST_WAKE_PIN,
	GYRO_INT_PIN,
	LM8502_LIGHTING_INT_IRQ_PIN,
	MAX8903B_GPIO_USB_CHG_MODE_PIN,
	MAX8903B_GPIO_DC_OK_PIN,
	TENDERLOIN_GPIO_WLAN_RST_N_PIN,
	TENDERLOIN_GPIO_HOST_WAKE_WL_PIN,
	TENDERLOIN_A6_0_TCK_PIN,
	TENDERLOIN_A6_0_WAKEUP_PIN,
	TENDERLOIN_A6_0_TDIO_PIN,
	TENDERLOIN_A6_0_MSM_IRQ_PIN,
	TENDERLOIN_A6_1_TCK_PIN,
	TENDERLOIN_A6_1_WAKEUP_PIN,
	TENDERLOIN_A6_1_TDIO_PIN,
	TENDERLOIN_A6_1_MSM_IRQ_PIN,
	VOL_UP_GPIO_PIN,
	VOL_DN_GPIO_PIN,
	TENDERLOIN_GPIO_3G_3V3_EN,
	NUM_TOPAZ_PINS
};

static int tenderloin_pins_wifi [] = {
	[MXT1386_TS_PEN_IRQ] = MXT1386_TS_PEN_IRQ_GPIO,
	[GPIO_CTP_WAKE_PIN] = GPIO_CTP_WAKE,
	[BT_RST_N_PIN] = BT_RST_N,
	[BT_POWER_PIN] = BT_POWER,
	[BT_WAKE_PIN] = BT_WAKE,
	[BT_HOST_WAKE_PIN] = BT_HOST_WAKE,
	[GYRO_INT_PIN] = TENDERLOIN_GYRO_INT,
	[LM8502_LIGHTING_INT_IRQ_PIN] = LM8502_LIGHTING_INT_IRQ_GPIO,
	[MAX8903B_GPIO_USB_CHG_MODE_PIN] = MAX8903B_GPIO_USB_CHG_MODE,
	[MAX8903B_GPIO_DC_OK_PIN] = MAX8903B_GPIO_DC_OK,
	[TENDERLOIN_GPIO_WLAN_RST_N_PIN] = TENDERLOIN_GPIO_WLAN_RST_N,
	[TENDERLOIN_GPIO_HOST_WAKE_WL_PIN] = TENDERLOIN_GPIO_HOST_WAKE_WL,
	[TENDERLOIN_A6_0_TCK_PIN] = TENDERLOIN_A6_0_TCK,
	[TENDERLOIN_A6_0_WAKEUP_PIN] = TENDERLOIN_A6_0_WAKEUP,
	[TENDERLOIN_A6_0_TDIO_PIN] = TENDERLOIN_A6_0_TDIO,
	[TENDERLOIN_A6_0_MSM_IRQ_PIN] = TENDERLOIN_A6_0_MSM_IRQ,
	[TENDERLOIN_A6_1_TCK_PIN] = TENDERLOIN_A6_1_TCK,
	[TENDERLOIN_A6_1_WAKEUP_PIN] = TENDERLOIN_A6_1_WAKEUP,
	[TENDERLOIN_A6_1_TDIO_PIN] = TENDERLOIN_A6_1_TDIO,
	[TENDERLOIN_A6_1_MSM_IRQ_PIN] = TENDERLOIN_A6_1_MSM_IRQ,
	[VOL_UP_GPIO_PIN] = VOL_UP_GPIO,
	[VOL_DN_GPIO_PIN] = VOL_DN_GPIO,
	[TENDERLOIN_GPIO_3G_3V3_EN] = GPIO_3G_3V3_EN,
};

static int tenderloin_pins_3g [] = {
	[MXT1386_TS_PEN_IRQ] = MXT1386_TS_PEN_IRQ_GPIO_3G,
	[GPIO_CTP_WAKE_PIN] = GPIO_CTP_WAKE_3G,
	[BT_RST_N_PIN] = BT_RST_N_3G,
	[BT_POWER_PIN] = BT_POWER_3G,
	[BT_WAKE_PIN] = BT_WAKE_3G,
	[BT_HOST_WAKE_PIN] = BT_HOST_WAKE_3G,
	[GYRO_INT_PIN] = TENDERLOIN_GYRO_INT_3G,
	[LM8502_LIGHTING_INT_IRQ_PIN] = LM8502_LIGHTING_INT_IRQ_GPIO_3G,
	[MAX8903B_GPIO_USB_CHG_MODE_PIN] = MAX8903B_GPIO_USB_CHG_MODE_3G,
	[MAX8903B_GPIO_DC_OK_PIN] = MAX8903B_GPIO_DC_OK_3G,
	[TENDERLOIN_GPIO_WLAN_RST_N_PIN] = TENDERLOIN_GPIO_WLAN_RST_N_3G,
	[TENDERLOIN_GPIO_HOST_WAKE_WL_PIN] = TENDERLOIN_GPIO_HOST_WAKE_WL_3G,
	[TENDERLOIN_A6_0_TCK_PIN] = TENDERLOIN_A6_0_TCK_3G,
	[TENDERLOIN_A6_0_WAKEUP_PIN] = TENDERLOIN_A6_0_WAKEUP_3G,
	[TENDERLOIN_A6_0_TDIO_PIN] = TENDERLOIN_A6_0_TDIO_3G,
	[TENDERLOIN_A6_0_MSM_IRQ_PIN] = TENDERLOIN_A6_0_MSM_IRQ_3G,
	[TENDERLOIN_A6_1_TCK_PIN] = TENDERLOIN_A6_1_TCK_3G,
	[TENDERLOIN_A6_1_WAKEUP_PIN] = TENDERLOIN_A6_1_WAKEUP_3G,
	[TENDERLOIN_A6_1_TDIO_PIN] = TENDERLOIN_A6_1_TDIO_3G,
	[TENDERLOIN_A6_1_MSM_IRQ_PIN] = TENDERLOIN_A6_1_MSM_IRQ_3G,
	[VOL_UP_GPIO_PIN] = VOL_UP_GPIO_3G,
	[VOL_DN_GPIO_PIN] = VOL_DN_GPIO_3G,
	[TENDERLOIN_GPIO_3G_3V3_EN] = GPIO_3G_3V3_EN,
};

static int tenderloin_pins_wifi_dvt [] = {
	[MXT1386_TS_PEN_IRQ] = MXT1386_TS_PEN_IRQ_GPIO,
	[GPIO_CTP_WAKE_PIN] = GPIO_CTP_WAKE,
	[BT_RST_N_PIN] = BT_RST_N,
	[BT_POWER_PIN] = BT_POWER,
	[BT_WAKE_PIN] = BT_WAKE,
	[BT_HOST_WAKE_PIN] = BT_HOST_WAKE,
	[GYRO_INT_PIN] = TENDERLOIN_GYRO_INT,
	[LM8502_LIGHTING_INT_IRQ_PIN] = LM8502_LIGHTING_INT_IRQ_GPIO,
	[MAX8903B_GPIO_USB_CHG_MODE_PIN] = MAX8903B_GPIO_USB_CHG_MODE,
	[MAX8903B_GPIO_DC_OK_PIN] = MAX8903B_GPIO_DC_OK,
	[TENDERLOIN_GPIO_WLAN_RST_N_PIN] = TENDERLOIN_GPIO_WLAN_RST_N,
	[TENDERLOIN_GPIO_HOST_WAKE_WL_PIN] = TENDERLOIN_GPIO_HOST_WAKE_WL,
	[TENDERLOIN_A6_0_TCK_PIN] = TENDERLOIN_A6_0_TCK,
	[TENDERLOIN_A6_0_WAKEUP_PIN] = TENDERLOIN_A6_0_WAKEUP,
	[TENDERLOIN_A6_0_TDIO_PIN] = TENDERLOIN_A6_0_TDIO,
	[TENDERLOIN_A6_0_MSM_IRQ_PIN] = TENDERLOIN_A6_0_MSM_IRQ_DVT,
	[TENDERLOIN_A6_1_TCK_PIN] = TENDERLOIN_A6_1_TCK,
	[TENDERLOIN_A6_1_WAKEUP_PIN] = TENDERLOIN_A6_1_WAKEUP,
	[TENDERLOIN_A6_1_TDIO_PIN] = TENDERLOIN_A6_1_TDIO,
	[TENDERLOIN_A6_1_MSM_IRQ_PIN] = TENDERLOIN_A6_1_MSM_IRQ_DVT,
	[VOL_UP_GPIO_PIN] = VOL_UP_GPIO,
	[VOL_DN_GPIO_PIN] = VOL_DN_GPIO,
	[TENDERLOIN_GPIO_3G_3V3_EN] = GPIO_3G_3V3_EN,
};

static int tenderloin_pins_3g_evt4[] = {
	[MXT1386_TS_PEN_IRQ] = MXT1386_TS_PEN_IRQ_GPIO_3G,
	[GPIO_CTP_WAKE_PIN] = GPIO_CTP_WAKE_3G,
	[BT_RST_N_PIN] = BT_RST_N_3G,
	[BT_POWER_PIN] = BT_POWER_3G,
	[BT_WAKE_PIN] = BT_WAKE_3G,
	[BT_HOST_WAKE_PIN] = BT_HOST_WAKE_3G,
	[GYRO_INT_PIN] = TENDERLOIN_GYRO_INT_3G,
	[LM8502_LIGHTING_INT_IRQ_PIN] = LM8502_LIGHTING_INT_IRQ_GPIO_3G,
	[MAX8903B_GPIO_USB_CHG_MODE_PIN] = MAX8903B_GPIO_USB_CHG_MODE_3G,
	[MAX8903B_GPIO_DC_OK_PIN] = MAX8903B_GPIO_DC_OK_3G,
	[TENDERLOIN_GPIO_WLAN_RST_N_PIN] = TENDERLOIN_GPIO_WLAN_RST_N_3G,
	[TENDERLOIN_GPIO_HOST_WAKE_WL_PIN] = TENDERLOIN_GPIO_HOST_WAKE_WL_3G,
	[TENDERLOIN_A6_0_TCK_PIN] = TENDERLOIN_A6_0_TCK_3G_DVT,
	[TENDERLOIN_A6_0_WAKEUP_PIN] = TENDERLOIN_A6_0_WAKEUP_3G,
	[TENDERLOIN_A6_0_TDIO_PIN] = TENDERLOIN_A6_0_TDIO_3G,
	[TENDERLOIN_A6_0_MSM_IRQ_PIN] = TENDERLOIN_A6_0_MSM_IRQ_3G_DVT,
	[TENDERLOIN_A6_1_TCK_PIN] = TENDERLOIN_A6_1_TCK_3G,
	[TENDERLOIN_A6_1_WAKEUP_PIN] = TENDERLOIN_A6_1_WAKEUP_3G,
	[TENDERLOIN_A6_1_TDIO_PIN] = TENDERLOIN_A6_1_TDIO_3G,
	[TENDERLOIN_A6_1_MSM_IRQ_PIN] = TENDERLOIN_A6_1_MSM_IRQ_3G_DVT,
	[VOL_UP_GPIO_PIN] = VOL_UP_GPIO_3G,
	[VOL_DN_GPIO_PIN] = VOL_DN_GPIO_3G,
	[TENDERLOIN_GPIO_3G_3V3_EN] = GPIO_3G_3V3_EN,
};


static int tenderloin_pins_3g_dvt [] = {
	[MXT1386_TS_PEN_IRQ] = MXT1386_TS_PEN_IRQ_GPIO_3G,
	[GPIO_CTP_WAKE_PIN] = GPIO_CTP_WAKE_3G,
	[BT_RST_N_PIN] = BT_RST_N_3G,
	[BT_POWER_PIN] = BT_POWER_3G,
	[BT_WAKE_PIN] = BT_WAKE_3G,
	[BT_HOST_WAKE_PIN] = BT_HOST_WAKE_3G,
	[GYRO_INT_PIN] = TENDERLOIN_GYRO_INT_3G,
	[LM8502_LIGHTING_INT_IRQ_PIN] = LM8502_LIGHTING_INT_IRQ_GPIO_3G,
	[MAX8903B_GPIO_USB_CHG_MODE_PIN] = MAX8903B_GPIO_USB_CHG_MODE_3G,
	[MAX8903B_GPIO_DC_OK_PIN] = MAX8903B_GPIO_DC_OK_3G,
	[TENDERLOIN_GPIO_WLAN_RST_N_PIN] = TENDERLOIN_GPIO_WLAN_RST_N_3G,
	[TENDERLOIN_GPIO_HOST_WAKE_WL_PIN] = TENDERLOIN_GPIO_HOST_WAKE_WL_3G,
	[TENDERLOIN_A6_0_TCK_PIN] = TENDERLOIN_A6_0_TCK_3G_DVT,
	[TENDERLOIN_A6_0_WAKEUP_PIN] = TENDERLOIN_A6_0_WAKEUP_3G,
	[TENDERLOIN_A6_0_TDIO_PIN] = TENDERLOIN_A6_0_TDIO_3G,
	[TENDERLOIN_A6_0_MSM_IRQ_PIN] = TENDERLOIN_A6_0_MSM_IRQ_3G_DVT,
	[TENDERLOIN_A6_1_TCK_PIN] = TENDERLOIN_A6_1_TCK_3G,
	[TENDERLOIN_A6_1_WAKEUP_PIN] = TENDERLOIN_A6_1_WAKEUP_3G,
	[TENDERLOIN_A6_1_TDIO_PIN] = TENDERLOIN_A6_1_TDIO_3G,
	[TENDERLOIN_A6_1_MSM_IRQ_PIN] = TENDERLOIN_A6_1_MSM_IRQ_3G_DVT,
	[VOL_UP_GPIO_PIN] = VOL_UP_GPIO_3G,
	[VOL_DN_GPIO_PIN] = VOL_DN_GPIO_3G,
	[TENDERLOIN_GPIO_3G_3V3_EN] = GPIO_3G_3V3_EN_DVT,
};

#endif
